name: Build, Zip, and Release

on:
  release:
    branches: [ "master" ]
    types: [published]

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install MSBuild
        run: |
          sudo apt-get update
          sudo apt-get install -y msbuild

      - name: Restore NuGet packages
        run: nuget restore .

      - name: Add Project Dependencies [#1]
        run: |
          mkdir ./bin
          cp ./DuckGame/lib/* ./bin

      - name: Build with AutoUpdater
        run: msbuild /m /p:Configuration=ReleaseAutoUpdater .

      - name: Zip binaries
        run: |
          sudo apt-get update
          sudo apt-get install -y zip
          mv ./bin ./DuckGameRebuilt
          cd ./DuckGameRebuilt && zip -r ../DuckGameRebuilt.zip ./* && cd ..

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./DuckGameRebuilt.zip
          overwrite: true

      - name: Add Project Dependencies [#2]
        run: |
          mkdir ./bin
          cp ./DuckGame/lib/* ./bin

      - name: Build without AutoUpdater
        run: msbuild /m /p:Configuration=Release .

      - name: Reorganize files for DGR mod
        run: | 
          mv ./bin ./Rebuilder/dgr
          find ./Rebuilder -maxdepth 1 ! \( -name "mod.conf" -o -name "Rebuilder.dll" \) -type f -exec rm {} +
          rm -r ./Rebuilder/build
          mkdir ./steammod
          mv ./Rebuilder ./steammod/Rebuilder

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14'

      - name: Install markdown to steam formatter
        run: npm install steamdown

      - name: Parse changelog from markdown to steam format
        id: parse_body
        run: |
          echo "${{ github.event.release.body }}" | sed 's/"/\\"/g; s/`/\\`/g' > release_body.txt
          echo "::set-output name=parsed_body::$(node -e \"console.log(require('steamdown').parse(require('fs').readFileSync('release_body.txt','utf-8')))\")"
          rm release_body.txt

      - name: Update DGR mod
        uses: AnarkisGaming/workshop@v1
        with:
          appID: 312530
          publishedFileID: ${{ vars.WORKSHOP_ID }}
          path: ./steammod
          changelog: ${{ steps.parse_body.outputs.parsed_body }}
        env:
          STEAM_ACCOUNT_NAME: "DuckGameRebuilt"
          STEAM_PASSWORD: ${{ secrets.STEAM_PASS }}
